규칙 불러오기 최적화
SMOSSW-TEAM2/Dan-ea-jang pull request #41
Opened 2023-05-26 02:48 UTC by fryti112

규칙 불러오기 if문 최적화 했습니다

2023-05-26 02:48 UTC, fryti112 reviewed
최적화 했습니다.

2023-05-26 13:26 UTC, ABETAKANOBU approved these changes
good

2023-05-28 13:46 UTC, ABETAKANOBU requested changes
혹시 이 코드 with문 써서 더 최적화 할 수 있는 것 같은데 해 봐도 되겠습니까?

2023-05-29 05:17 UTC, fryti112 commented
> 혹시 이 코드 with문 써서 더 최적화 할 수 있는 것 같은데 해 봐도 되겠습니까?

네
수정 가능하게 설정 되어있으니 수정해서 올리시면 확인 하겠습니다.

2023-05-30 04:36 UTC, ABETAKANOBU commented
확인부탁드립니다

2023-05-30 05:31 UTC, ABETAKANOBU approved these changes

2023-05-30 12:43 UTC, merged