Update 단어장_L_kr.yml
SMOSSW-TEAM2/Dan-ea-jang pull request #44
Opened 2023-05-28 15:26 UTC by geonwoo237

단어장 K -> L추가했습니다.

2023-05-29 04:51 UTC, fryti112 approved these changes
good

2023-05-29 04:51 UTC, fryti112 approved these changes
good

2023-05-29 04:51 UTC, fryti112 approved these changes
good

2023-05-29 07:52 UTC, ABETAKANOBU approved these changes

2023-05-30 05:19 UTC, gyeonginkang approved these changes

2023-05-31 11:11 UTC, fryti112 requested changes
하나의 단어에 한 가지 뜻만 있게 해주시고 단어 설명은 빼도 됩니다.
공백을 기준으로 딕셔너리화 시키는 방식이라 문제가 생깁니다.

2023-05-31 11:14 UTC, closed without merging

2023-06-01 14:59 UTC, geonwoo237 commented
네